//This is our (incomplete) array

var teams = [
  "AFC Bournemouth",
  "Arsenal",
  "Burnley",
  "Chelsea"
]

//These commands output text to the log.

console.log(teams[0]); // This Would output 'AFC Bournemouth'
console.log(teams[3]); // This Would output 'Chelsea'

//Now we replace the number with a var generated by the user

var chosenteam = 2;

console.log(teams[chosenteam]); //This would output 'Burnley'
